#pragma once

#include <stdint.h>
#include <WinError.h>

namespace WRep
{
	enum ERRORS_REPLAY_ANALYZER
	{
		ERR_UNKNOWN = 0x200,
		ERR_INVALID_ARG,
		ERR_INVALID_PATH,
		ERR_MAP_UNKNOWN_FORMAT,
		ERR_REP_NOT_SUPPORT,
		ERR_ZLIB_FAILED,
		ERR_REP_UNKNOWN_FORMAT,
		ERR_NOT_FOUND_REPLAY,
		ERR_NOT_FOUND_RESOURCE,
		ERR_FAILD_CREATE_PROCESS,
		ERR_UNSUPPORTED_VERSION,
		ERR_NOT_FOUND_MODULE,
		ERR_INVALID_PLAYER_ID,
		ERR_NOT_FOUND_MAP = 0x401,
		ERR_NOT_FOUND_PATCH,
		ERR_NOT_FOUND_CONFIG,
	};
}
